// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ShoppingListApi.Models
{
    public interface IShoppingListItem
    {
        bool IsPickedUp { get; set; }
        int ItemId { get; set; }
        string ItemName { get; set; }
    }
}