// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoppingListApi.Models;

public partial class ShoppingListItem : IShoppingListItem
{
    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public bool IsPickedUp { get; set; }
}